### ISSUE TITLE
Tutorials ordering

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#276]
**Is your feature request related to a problem? Please describe.**

I'd like a means for ordering my tutorials rather than the current default of sorting them.

This may already be available, but I've missed it in the very nice docs you provide.

**Describe the solution you'd like**

A reasonable solution would be to provide an array of the tutorial names in the desired order.
There are potential errors if:

* Only some of the tutorials are in the array 
* The names in the array are misspelled.

I think it would be fine if an error was raised during the build step if these occurred.

**Describe alternatives you've considered**

I could just add a number to the name of the tutorials: 0 - Getting Started, 1 - Browser, .. etc.

**Additional context**

Here's my current tutorials list:

![Snap 01 16 24-15 41 05](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/124366/bd04b7bb-5b77-4659-9c37-0c13ce407b44)

**Comment by backspaces** [comment]
The numbering stunt has annoyances, not the least of which is renumbering them when you think of a new tutorial that is in the middle of the others! And the numbering is sort of noisy, detracting from the simple name.

Also, numbering runs into problems when you go past 9 to 10:

![Snap 01 16 24-16 44 48](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/124366/e2f7cafa-e271-4755-8ac5-cc26a21840fa)

**Comment by backspaces** [comment]
And here's another drawback: the numbers appear in the docs themselves. In the example below, the tutorial for Browser appears as 2 - Browser in the heading of the tutorial.

![Snap 01 16 24-16 51 52](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/124366/ec0bb047-cedc-4e3d-82ed-f05fd8498164)

**Comment by ankitskvmdam** [comment]
Thanks for creating this issue. Currently there is no option for ordering tutorials.

I will look for the ways to support this.

**Comment by backspaces** [comment]
Turns out that the numbers are not an issue and the team liked them. So not in a hurry. If I go past 9 I'll need it tho :)

**Comment by ankitskvmdam** [comment]
Hi, I found one solution it is a bit similar to what you are doing.

### Solution

This solution is based on this document: https://jsdoc.app/about-tutorials.
The plan is to use the inbuilt JSDoc sorting. As you have already figured out, it sorts filename name in ascending order.

We can prefix tutorial's filename with numbers (what you are doing) or with alphabets. We can do 0 to 9 and then 91-99 (instead of 10 - 19) and then 991 - 999 and so on. Another option is we can do a-z and then za to zz and so on.

If we prefix the filename of the tutorial then it will be shown in the generated HTML file. To have a custom title there is an option to rename the title of a tutorial using `tutorial.json`. In the folder where we have all the tutorials we can create a new file called `tutorials.json` and we can do something as following:

```json5
// ./src/tutorials/tutorials.json

{
    "a-Javascript": {
        "title": "Javascript"
    },
    "b-Browser":{
        "title": "Browser"
    },
    "c-AgentScript": {
        "title": "AgentScript"
    }
    //  upto z and then
    "za-SomethingElse1":{
        "title": "Something Else 1"
    },
    "zb-SomethingElse2": {
        "title": "Something Else 2"
    }
}

// or

{
    "1-Javascript": {
        "title": "Javascript"
    },
    "2-Browser":{
        "title": "Browser"
    },
    "3-AgentScript": {
        "title": "AgentScript"
    }
    //  upto 9 and then
    "91-SomethingElse1":{
        "title": "Something Else 1"
    },
    "92-SomethingElse2": {
        "title": "Something Else 2"
    }
}
```

### Thoughts

I tried to find a sophisticated solution, however jsdoc's Tutorial class doesn't save much information (like config.) [See](https://github.com/jsdoc/jsdoc/blob/releases/4.0/lib/jsdoc/tutorial.js#L44), and I didn't able to find any option to inject additional properties. 

The downside of above approach are:
1. filename/file path looks ugly.
2. It might be difficult to do reordering.

However, I guess this is the only way provided by JSDoc to sort tutorials.

**Comment by backspaces** [comment]
Fascinating! I'll close this, and thanjs for the info and help!
